apiVersion: v1
kind: Service
metadata:
  name: web-game-service
  labels:
    app: web-game
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 31004
  selector:
    app: web-game
